--- #YAML:1.0
name:               CLI-Dispatch
version:            0.11_01
abstract:           simple CLI dispatcher
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Unload:        0
    Encode:               0
    File::Spec:           0
    Getopt::Long:         0
    Log::Dump:            0
    Path::Extended:       0
    Pod::Simple:          0
    String::CamelCase:    0
    Term::Encoding:       0
    Test::Classy:         0.04
    Test::More:           0.47
    Test::UseAllModules:  0.09
    Try::Tiny:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
